version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  prometheus_data:

services:
  application:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    networks:
      - app-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.4.1
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    networks:
      - app-network

  grafana:
    container_name: grafana
    image: grafana/grafana:12.0.2
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - prometheus
