export enum ServiceStatus {
  SUCCESS = 'SUCCESS',
  CREATED = 'CREATED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
}
